FROM node:20.10.0-slim AS base
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable pnpm && corepack prepare pnpm@8.12.1 --activate
WORKDIR /app

COPY . .

RUN pnpm install -r --shamefully-hoist

RUN pnpm run build:dev --filter shared-ui

FROM base AS system
WORKDIR /app/apps/system
EXPOSE 5173
