FROM golang:1.21.5-alpine as builder

WORKDIR /app

ARG GITHUB_TOKEN

RUN apk update && \
    apk add --no-cache git=2.43.0-r0 ca-certificates=20230506-r0 tzdata=2023d-r0 && \
    git config --global url."https://${GITHUB_TOKEN}:x-oauth-basic@github.com/ryo034/".insteadOf "https://github.com/ryo034/"

COPY . .

# For Hot Reload & Debug
ARG CGO_ENABLED=0
ARG GOOS=linux
ARG GOARCH=amd64
RUN go mod tidy && \
	go install github.com/cosmtrek/air@latest && \
	go get github.com/go-delve/delve/cmd/dlv && \
	go build -buildvcs=false -o /go/bin/dlv github.com/go-delve/delve/cmd/dlv

EXPOSE 19004

CMD ["air", "-c", ".air.toml"]
