version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "07:00"
      timezone: "Asia/Tokyo"

  - package-ecosystem: "gomod"
    directory: "/apps/system/api"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "07:00"
      timezone: "Asia/Tokyo"
    groups:
      dependencies:
        patterns:
          - "*"
        update-types:
          - patch
          - minor
          - major

  - package-ecosystem: "npm"
    directory: "/apps/system/client"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "07:00"
      timezone: "Asia/Tokyo"
    open-pull-requests-limit: 1
    groups:
      dependencies:
        patterns:
          - "*"
        update-types:
          - patch
          - minor
          - major

  - package-ecosystem: "npm"
    directory: "/packages/typescript/ui"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "Asia/Tokyo"
    open-pull-requests-limit: 1
    groups:
      dependencies:
        patterns:
          - "*"
        update-types:
          - patch
          - minor
          - major
