// Code generated by ogen, DO NOT EDIT.
package openapi

type APIV1AuthOAuthPostRes interface {
	aPIV1AuthOAuthPostRes()
}

type APIV1AuthOtpPostRes interface {
	aPIV1AuthOtpPostRes()
}

type APIV1AuthOtpVerifyPostRes interface {
	aPIV1AuthOtpVerifyPostRes()
}

type APIV1MeGetRes interface {
	aPIV1MeGetRes()
}

type APIV1MeProfilePutRes interface {
	aPIV1MeProfilePutRes()
}

type APIV1PingGetRes interface {
	aPIV1PingGetRes()
}

type APIV1WorkspacesGetRes interface {
	aPIV1WorkspacesGetRes()
}

type APIV1WorkspacesPostRes interface {
	aPIV1WorkspacesPostRes()
}

type LoginRes interface {
	loginRes()
}
