// Code generated by ogen, DO NOT EDIT.
package openapi

type APIV1AcceptInvitationRes interface {
	aPIV1AcceptInvitationRes()
}

type APIV1AuthByOAuthRes interface {
	aPIV1AuthByOAuthRes()
}

type APIV1AuthByOtpRes interface {
	aPIV1AuthByOtpRes()
}

type APIV1CreateWorkspaceRes interface {
	aPIV1CreateWorkspaceRes()
}

type APIV1GetInvitationByTokenRes interface {
	aPIV1GetInvitationByTokenRes()
}

type APIV1GetInvitationsRes interface {
	aPIV1GetInvitationsRes()
}

type APIV1GetMeRes interface {
	aPIV1GetMeRes()
}

type APIV1GetMembersRes interface {
	aPIV1GetMembersRes()
}

type APIV1GetWorkspacesRes interface {
	aPIV1GetWorkspacesRes()
}

type APIV1InviteMultipleUsersRes interface {
	aPIV1InviteMultipleUsersRes()
}

type APIV1LeaveWorkspaceRes interface {
	aPIV1LeaveWorkspaceRes()
}

type APIV1ProcessInvitationEmailRes interface {
	aPIV1ProcessInvitationEmailRes()
}

type APIV1ProcessInvitationOAuthRes interface {
	aPIV1ProcessInvitationOAuthRes()
}

type APIV1RemoveMemberRes interface {
	aPIV1RemoveMemberRes()
}

type APIV1RemoveProfilePhotoRes interface {
	aPIV1RemoveProfilePhotoRes()
}

type APIV1ResendInvitationRes interface {
	aPIV1ResendInvitationRes()
}

type APIV1RevokeInvitationRes interface {
	aPIV1RevokeInvitationRes()
}

type APIV1UpdateMeMemberProfileRes interface {
	aPIV1UpdateMeMemberProfileRes()
}

type APIV1UpdateMemberRoleRes interface {
	aPIV1UpdateMemberRoleRes()
}

type APIV1UpdateProfilePhotoRes interface {
	aPIV1UpdateProfilePhotoRes()
}

type APIV1UpdateProfileRes interface {
	aPIV1UpdateProfileRes()
}

type APIV1UpdateWorkspaceRes interface {
	aPIV1UpdateWorkspaceRes()
}

type APIV1VerifyOTPRes interface {
	aPIV1VerifyOTPRes()
}

type PingRes interface {
	pingRes()
}
