// Code generated by ogen, DO NOT EDIT.

package openapi

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// Login implements login operation.
//
// Login.
//
// POST /login
func (UnimplementedHandler) Login(ctx context.Context) (r LoginRes, _ error) {
	return r, ht.ErrNotImplemented
}

// MeGet implements GET /me operation.
//
// Returns the admin user.
//
// GET /me
func (UnimplementedHandler) MeGet(ctx context.Context) (r MeGetRes, _ error) {
	return r, ht.ErrNotImplemented
}

// OtpAuthPost implements POST /otp/auth operation.
//
// Send Timed One Time Password (TOTP) to user.
//
// POST /otp/auth
func (UnimplementedHandler) OtpAuthPost(ctx context.Context, req *OtpAuthPostReq) (r OtpAuthPostRes, _ error) {
	return r, ht.ErrNotImplemented
}

// OtpVerifyPost implements POST /otp/verify operation.
//
// Verify OTP sent by user.
//
// POST /otp/verify
func (UnimplementedHandler) OtpVerifyPost(ctx context.Context, req *OtpVerifyPostReq) (r OtpVerifyPostRes, _ error) {
	return r, ht.ErrNotImplemented
}

// PingGet implements GET /ping operation.
//
// Checks if the server is running.
//
// GET /ping
func (UnimplementedHandler) PingGet(ctx context.Context) (r PingGetRes, _ error) {
	return r, ht.ErrNotImplemented
}

// PingPost implements POST /ping operation.
//
// Checks if the server is running.
//
// POST /ping
func (UnimplementedHandler) PingPost(ctx context.Context, req OptPingPostReq) (r PingPostRes, _ error) {
	return r, ht.ErrNotImplemented
}

// SignUp implements sign_up operation.
//
// Sign Up.
//
// POST /sign_up
func (UnimplementedHandler) SignUp(ctx context.Context, req *SignUpReq) (r SignUpRes, _ error) {
	return r, ht.ErrNotImplemented
}
