// Code generated by ogen, DO NOT EDIT.

package openapi

// RFC7807 - https://datatracker.ietf.org/doc/html/rfc7807.
type BadRequestError struct {
	// The HTTP status code generated for this occurrence of the problem.
	Status OptInt `json:"status"`
	// Error type.
	Type OptString `json:"type"`
	// A short, human-readable summary of the problem type.
	Title OptString `json:"title"`
	// A human-readable explanation specific to this occurrence of the problem.
	Detail OptString `json:"detail"`
	// Error code.
	Code OptString `json:"code"`
}

// GetStatus returns the value of Status.
func (s *BadRequestError) GetStatus() OptInt {
	return s.Status
}

// GetType returns the value of Type.
func (s *BadRequestError) GetType() OptString {
	return s.Type
}

// GetTitle returns the value of Title.
func (s *BadRequestError) GetTitle() OptString {
	return s.Title
}

// GetDetail returns the value of Detail.
func (s *BadRequestError) GetDetail() OptString {
	return s.Detail
}

// GetCode returns the value of Code.
func (s *BadRequestError) GetCode() OptString {
	return s.Code
}

// SetStatus sets the value of Status.
func (s *BadRequestError) SetStatus(val OptInt) {
	s.Status = val
}

// SetType sets the value of Type.
func (s *BadRequestError) SetType(val OptString) {
	s.Type = val
}

// SetTitle sets the value of Title.
func (s *BadRequestError) SetTitle(val OptString) {
	s.Title = val
}

// SetDetail sets the value of Detail.
func (s *BadRequestError) SetDetail(val OptString) {
	s.Detail = val
}

// SetCode sets the value of Code.
func (s *BadRequestError) SetCode(val OptString) {
	s.Code = val
}

func (*BadRequestError) signUpRes() {}

type Bearer struct {
	Token string
}

// GetToken returns the value of Token.
func (s *Bearer) GetToken() string {
	return s.Token
}

// SetToken sets the value of Token.
func (s *Bearer) SetToken(val string) {
	s.Token = val
}

// RFC7807 - https://datatracker.ietf.org/doc/html/rfc7807.
type InternalServerError struct {
	// The HTTP status code generated for this occurrence of the problem.
	Status OptInt `json:"status"`
	// Error type.
	Type OptString `json:"type"`
	// A short, human-readable summary of the problem type.
	Title OptString `json:"title"`
	// A human-readable explanation specific to this occurrence of the problem.
	Detail OptString `json:"detail"`
	// Error code.
	Code OptString `json:"code"`
}

// GetStatus returns the value of Status.
func (s *InternalServerError) GetStatus() OptInt {
	return s.Status
}

// GetType returns the value of Type.
func (s *InternalServerError) GetType() OptString {
	return s.Type
}

// GetTitle returns the value of Title.
func (s *InternalServerError) GetTitle() OptString {
	return s.Title
}

// GetDetail returns the value of Detail.
func (s *InternalServerError) GetDetail() OptString {
	return s.Detail
}

// GetCode returns the value of Code.
func (s *InternalServerError) GetCode() OptString {
	return s.Code
}

// SetStatus sets the value of Status.
func (s *InternalServerError) SetStatus(val OptInt) {
	s.Status = val
}

// SetType sets the value of Type.
func (s *InternalServerError) SetType(val OptString) {
	s.Type = val
}

// SetTitle sets the value of Title.
func (s *InternalServerError) SetTitle(val OptString) {
	s.Title = val
}

// SetDetail sets the value of Detail.
func (s *InternalServerError) SetDetail(val OptString) {
	s.Detail = val
}

// SetCode sets the value of Code.
func (s *InternalServerError) SetCode(val OptString) {
	s.Code = val
}

func (*InternalServerError) loginRes()   {}
func (*InternalServerError) meGetRes()   {}
func (*InternalServerError) pingGetRes() {}
func (*InternalServerError) signUpRes()  {}

// Ref: #/components/schemas/Me
type Me struct {
	EmailVerified bool           `json:"emailVerified"`
	MultiFactor   OptMultiFactor `json:"multiFactor"`
	Member        Member         `json:"member"`
}

// GetEmailVerified returns the value of EmailVerified.
func (s *Me) GetEmailVerified() bool {
	return s.EmailVerified
}

// GetMultiFactor returns the value of MultiFactor.
func (s *Me) GetMultiFactor() OptMultiFactor {
	return s.MultiFactor
}

// GetMember returns the value of Member.
func (s *Me) GetMember() Member {
	return s.Member
}

// SetEmailVerified sets the value of EmailVerified.
func (s *Me) SetEmailVerified(val bool) {
	s.EmailVerified = val
}

// SetMultiFactor sets the value of MultiFactor.
func (s *Me) SetMultiFactor(val OptMultiFactor) {
	s.MultiFactor = val
}

// SetMember sets the value of Member.
func (s *Me) SetMember(val Member) {
	s.Member = val
}

func (*Me) loginRes()  {}
func (*Me) meGetRes()  {}
func (*Me) signUpRes() {}

// Ref: #/components/schemas/Member
type Member struct {
	IdNumber OptString `json:"idNumber"`
	User     User      `json:"user"`
}

// GetIdNumber returns the value of IdNumber.
func (s *Member) GetIdNumber() OptString {
	return s.IdNumber
}

// GetUser returns the value of User.
func (s *Member) GetUser() User {
	return s.User
}

// SetIdNumber sets the value of IdNumber.
func (s *Member) SetIdNumber(val OptString) {
	s.IdNumber = val
}

// SetUser sets the value of User.
func (s *Member) SetUser(val User) {
	s.User = val
}

// Ref: #/components/schemas/MultiFactor
type MultiFactor struct {
	FactorId    string `json:"factorId"`
	PhoneNumber string `json:"phoneNumber"`
}

// GetFactorId returns the value of FactorId.
func (s *MultiFactor) GetFactorId() string {
	return s.FactorId
}

// GetPhoneNumber returns the value of PhoneNumber.
func (s *MultiFactor) GetPhoneNumber() string {
	return s.PhoneNumber
}

// SetFactorId sets the value of FactorId.
func (s *MultiFactor) SetFactorId(val string) {
	s.FactorId = val
}

// SetPhoneNumber sets the value of PhoneNumber.
func (s *MultiFactor) SetPhoneNumber(val string) {
	s.PhoneNumber = val
}

// NewOptInt returns new OptInt with value set to v.
func NewOptInt(v int) OptInt {
	return OptInt{
		Value: v,
		Set:   true,
	}
}

// OptInt is optional int.
type OptInt struct {
	Value int
	Set   bool
}

// IsSet returns true if OptInt was set.
func (o OptInt) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt) Reset() {
	var v int
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt) SetTo(v int) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt) Get() (v int, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt) Or(d int) int {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptMultiFactor returns new OptMultiFactor with value set to v.
func NewOptMultiFactor(v MultiFactor) OptMultiFactor {
	return OptMultiFactor{
		Value: v,
		Set:   true,
	}
}

// OptMultiFactor is optional MultiFactor.
type OptMultiFactor struct {
	Value MultiFactor
	Set   bool
}

// IsSet returns true if OptMultiFactor was set.
func (o OptMultiFactor) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptMultiFactor) Reset() {
	var v MultiFactor
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptMultiFactor) SetTo(v MultiFactor) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptMultiFactor) Get() (v MultiFactor, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptMultiFactor) Or(d MultiFactor) MultiFactor {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptSignUpReq returns new OptSignUpReq with value set to v.
func NewOptSignUpReq(v SignUpReq) OptSignUpReq {
	return OptSignUpReq{
		Value: v,
		Set:   true,
	}
}

// OptSignUpReq is optional SignUpReq.
type OptSignUpReq struct {
	Value SignUpReq
	Set   bool
}

// IsSet returns true if OptSignUpReq was set.
func (o OptSignUpReq) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptSignUpReq) Reset() {
	var v SignUpReq
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptSignUpReq) SetTo(v SignUpReq) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptSignUpReq) Get() (v SignUpReq, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptSignUpReq) Or(d SignUpReq) SignUpReq {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// PingGetOK is response for PingGet operation.
type PingGetOK struct{}

func (*PingGetOK) pingGetRes() {}

type SignUpReq struct {
	// First Name.
	FirstName OptString `json:"first_name"`
	// Last Name.
	LastName OptString `json:"last_name"`
}

// GetFirstName returns the value of FirstName.
func (s *SignUpReq) GetFirstName() OptString {
	return s.FirstName
}

// GetLastName returns the value of LastName.
func (s *SignUpReq) GetLastName() OptString {
	return s.LastName
}

// SetFirstName sets the value of FirstName.
func (s *SignUpReq) SetFirstName(val OptString) {
	s.FirstName = val
}

// SetLastName sets the value of LastName.
func (s *SignUpReq) SetLastName(val OptString) {
	s.LastName = val
}

// RFC7807 - https://datatracker.ietf.org/doc/html/rfc7807.
type UnauthorizedError struct {
	// The HTTP status code generated for this occurrence of the problem.
	Status OptInt `json:"status"`
	// Error type.
	Type OptString `json:"type"`
	// A short, human-readable summary of the problem type.
	Title OptString `json:"title"`
	// A human-readable explanation specific to this occurrence of the problem.
	Detail OptString `json:"detail"`
	// Error code.
	Code OptString `json:"code"`
}

// GetStatus returns the value of Status.
func (s *UnauthorizedError) GetStatus() OptInt {
	return s.Status
}

// GetType returns the value of Type.
func (s *UnauthorizedError) GetType() OptString {
	return s.Type
}

// GetTitle returns the value of Title.
func (s *UnauthorizedError) GetTitle() OptString {
	return s.Title
}

// GetDetail returns the value of Detail.
func (s *UnauthorizedError) GetDetail() OptString {
	return s.Detail
}

// GetCode returns the value of Code.
func (s *UnauthorizedError) GetCode() OptString {
	return s.Code
}

// SetStatus sets the value of Status.
func (s *UnauthorizedError) SetStatus(val OptInt) {
	s.Status = val
}

// SetType sets the value of Type.
func (s *UnauthorizedError) SetType(val OptString) {
	s.Type = val
}

// SetTitle sets the value of Title.
func (s *UnauthorizedError) SetTitle(val OptString) {
	s.Title = val
}

// SetDetail sets the value of Detail.
func (s *UnauthorizedError) SetDetail(val OptString) {
	s.Detail = val
}

// SetCode sets the value of Code.
func (s *UnauthorizedError) SetCode(val OptString) {
	s.Code = val
}

func (*UnauthorizedError) signUpRes() {}

// Ref: #/components/schemas/User
type User struct {
	UserId      string    `json:"userId"`
	Email       string    `json:"email"`
	Name        string    `json:"name"`
	PhoneNumber OptString `json:"phoneNumber"`
}

// GetUserId returns the value of UserId.
func (s *User) GetUserId() string {
	return s.UserId
}

// GetEmail returns the value of Email.
func (s *User) GetEmail() string {
	return s.Email
}

// GetName returns the value of Name.
func (s *User) GetName() string {
	return s.Name
}

// GetPhoneNumber returns the value of PhoneNumber.
func (s *User) GetPhoneNumber() OptString {
	return s.PhoneNumber
}

// SetUserId sets the value of UserId.
func (s *User) SetUserId(val string) {
	s.UserId = val
}

// SetEmail sets the value of Email.
func (s *User) SetEmail(val string) {
	s.Email = val
}

// SetName sets the value of Name.
func (s *User) SetName(val string) {
	s.Name = val
}

// SetPhoneNumber sets the value of PhoneNumber.
func (s *User) SetPhoneNumber(val OptString) {
	s.PhoneNumber = val
}
