openapi: 3.0.2
info:
  title: System API
  description: System API
  version: 1.0.0
tags:
  - name: Health
    description: Health Check
paths:
  /ping:
    $ref: "./paths/ping.yaml#/ping"
  /me:
    $ref: "./paths/me.yaml#/me"
  /sign_up:
    $ref: "./paths/sign_up.yaml#/sign_up"
  /login:
    $ref: "./paths/login.yaml#/login"

components:
  securitySchemes:
    $ref: "./components/securitySchemes/index.yaml#/securitySchemes"
  schemas:
    User:
      $ref: "./components/schemas/me.yaml#/User"
    MultiFactor:
      $ref: "./components/schemas/me.yaml#/MultiFactor"
    Me:
      $ref: "./components/schemas/me.yaml#/Me"
  responses:
    GeneralError:
      $ref: "./components/responses/error.yaml#/components/responses/GeneralError"
    Unauthorized:
      $ref: "./components/responses/error.yaml#/components/responses/Unauthorized"
    NotFound:
      $ref: "./components/responses/error.yaml#/components/responses/NotFound"
    BadRequest:
      $ref: "./components/responses/error.yaml#/components/responses/BadRequest"
    InternalServerError:
      $ref: "./components/responses/error.yaml#/components/responses/InternalServerError"
