openapi: 3.0.2
info:
  title: System API
  description: System API
  version: 1.0.0
paths:
  /api/v1/ping:
    $ref: "./paths/ping.yaml#/ping"
  /api/v1/auth/otp:
    $ref: "./paths/auth.yaml#/authByOtp"
  /api/v1/auth/otp/verify:
    $ref: "./paths/auth.yaml#/verify"
  /api/v1/auth/oauth:
    $ref: "./paths/auth.yaml#/oauth"
  /api/v1/me:
    $ref: "./paths/me.yaml#/me"
  /api/v1/me/update-name:
    $ref: "./paths/me.yaml#/updateName"
  /api/v1/login:
    $ref: "./paths/login.yaml#/login"
  /api/v1/workspaces:
    $ref: "./paths/workspace.yaml#/workspaces"

components:
  securitySchemes:
    $ref: "./components/securitySchemes/index.yaml#/securitySchemes"
  schemas:
    JwtToken:
      $ref: "./components/schemas/auth.yaml#/JwtToken"
    User:
      $ref: "./components/schemas/user.yaml#/User"
    MultiFactor:
      $ref: "./components/schemas/me.yaml#/MultiFactor"
    Workspace:
      $ref: "./components/schemas/workspace.yaml#/Workspace"
    Workspaces:
      $ref: "./components/schemas/workspace.yaml#/Workspaces"
    Member:
      $ref: "./components/schemas/member.yaml#/Member"
    MemberProfile:
      $ref: "./components/schemas/member.yaml#/MemberProfile"
    MembershipPeriod:
      $ref: "./components/schemas/membership.yaml#/MembershipPeriod"
    Me:
      $ref: "./components/schemas/me.yaml#/Me"
  requestBodies:
    AuthByOtpPost:
      $ref: "./components/requestBodies/auth.yaml#/AuthByOtpPost"
    AuthVerifyPost:
      $ref: "./components/requestBodies/auth.yaml#/AuthVerifyPost"
    CreateWorkspace:
      $ref: "./components/requestBodies/workspace.yaml#/CreateWorkspace"
    UpdateName:
      $ref: "./components/requestBodies/me.yaml#/UpdateName"
  responses:
    GeneralError:
      $ref: "./components/responses/error.yaml#/components/responses/GeneralError"
    BadRequestError:
      $ref: "./components/responses/error.yaml#/components/responses/BadRequestError"
    NotFoundError:
      $ref: "./components/responses/error.yaml#/components/responses/NotFoundError"
    UnauthorizedError:
      $ref: "./components/responses/error.yaml#/components/responses/UnauthorizedError"
    ConflictError:
      $ref: "./components/responses/error.yaml#/components/responses/ConflictError"
    TooManyRequestsError:
      $ref: "./components/responses/error.yaml#/components/responses/TooManyRequestsError"
    InternalServerError:
      $ref: "./components/responses/error.yaml#/components/responses/InternalServerError"
