openapi: 3.0.2
info:
  title: System API
  description: System API
  version: 1.0.0
tags:
  - name: Health
    description: Health Check
paths:
  /ping:
    $ref: "./paths/ping.yaml#/ping"
  /me:
    $ref: "./paths/me.yaml#/me"
  /sign_up:
    $ref: "./paths/sign_up.yaml#/sign_up"
  /login:
    $ref: "./paths/login.yaml#/login"

components:
  securitySchemes:
    $ref: "./components/securitySchemes/index.yaml#/securitySchemes"
  schemas:
    User:
      $ref: "./components/schemas/user.yaml#/User"
    MultiFactor:
      $ref: "./components/schemas/me.yaml#/MultiFactor"
    Workspace:
      $ref: "./components/schemas/workspace.yaml#/Workspace"
    Member:
      $ref: "./components/schemas/member.yaml#/Member"
    MemberProfile:
      $ref: "./components/schemas/member.yaml#/MemberProfile"
    MembershipPeriod:
      $ref: "./components/schemas/membership.yaml#/MembershipPeriod"
    Me:
      $ref: "./components/schemas/me.yaml#/Me"
  responses:
    GeneralError:
      $ref: "./components/responses/error.yaml#/components/responses/GeneralError"
    UnauthorizedError:
      $ref: "./components/responses/error.yaml#/components/responses/UnauthorizedError"
    NotFoundError:
      $ref: "./components/responses/error.yaml#/components/responses/NotFoundError"
    BadRequestError:
      $ref: "./components/responses/error.yaml#/components/responses/BadRequestError"
    InternalServerError:
      $ref: "./components/responses/error.yaml#/components/responses/InternalServerError"
