openapi: 3.0.2
info:
  title: System API
  description: System API
  version: 1.0.0
paths:
  # Unauthenticated
  /ping:
    $ref: "./paths/ping.yaml#/ping"
  /api/v1/auth/otp:
    $ref: "./paths/auth.yaml#/authByOtp"
  /api/v1/auth/otp/verify:
    $ref: "./paths/auth.yaml#/verify"
  /api/v1/auth/invitations/process/email:
    $ref: "./paths/auth.yaml#/invitationProcessEmail"
  /api/v1/auth/invitations/process/oauth:
    $ref: "./paths/auth.yaml#/invitationProcessOAuth"
  /api/v1/auth/invitations:
    $ref: "./paths/auth.yaml#/invitation"
  /api/v1/auth/oauth:
    $ref: "./paths/auth.yaml#/oauth"
  # Me
  /api/v1/me:
    $ref: "./paths/me.yaml#/me"
  /api/v1/me/profile:
    $ref: "./paths/me.yaml#/profile"
  /api/v1/me/profile/photo:
    $ref: "./paths/me.yaml#/profilePhoto"
  /api/v1/me/member/profile:
    $ref: "./paths/me.yaml#/memberProfile"
  /api/v1/me/workspace/leave:
    $ref: "./paths/me.yaml#/leaveWorkspace"
  # Workspaces
  /api/v1/workspaces:
    $ref: "./paths/workspace.yaml#/workspaces"
  /api/v1/workspaces/{workspaceId}:
    $ref: "./paths/workspace.yaml#/workspace"
  /api/v1/members:
    $ref: "./paths/member.yaml#/members"
  /api/v1/members/{memberId}:
    $ref: "./paths/member.yaml#/member"
  /api/v1/members/{memberId}/role:
    $ref: "./paths/member.yaml#/memberRole"
  /api/v1/invitations:
    $ref: "./paths/member.yaml#/invitations"
  /api/v1/members/invitations/bulk:
    $ref: "./paths/member.yaml#/invitationsBulk"
  /api/v1/members/invitations/{invitationId}/accept:
    $ref: "./paths/me.yaml#/invitationsAccept"
  /api/v1/members/invitations/{invitationId}/revoke:
    $ref: "./paths/member.yaml#/invitationsRevoke"
  /api/v1/members/invitations/{invitationId}/resend:
    $ref: "./paths/member.yaml#/resendInvitations"

components:
  securitySchemes:
    $ref: "./components/securitySchemes/index.yaml#/securitySchemes"
  schemas:
    JwtToken:
      $ref: "./components/schemas/auth.yaml#/JwtToken"
    AuthProvider:
      $ref: "./components/schemas/auth.yaml#/AuthProvider"
    User:
      $ref: "./components/schemas/user.yaml#/User"
    MultiFactor:
      $ref: "./components/schemas/me.yaml#/MultiFactor"
    Workspace:
      $ref: "./components/schemas/workspace.yaml#/Workspace"
    Workspaces:
      $ref: "./components/schemas/workspace.yaml#/Workspaces"
    Inviter:
      $ref: "./components/schemas/workspace.yaml#/Inviter"
    Member:
      $ref: "./components/schemas/member.yaml#/Member"
    MemberRole:
      $ref: "./components/schemas/member.yaml#/MemberRole"
    MemberProfile:
      $ref: "./components/schemas/member.yaml#/MemberProfile"
    Members:
      $ref: "./components/schemas/member.yaml#/Members"
    Invitation:
      $ref: "./components/schemas/invitation.yaml#/Invitation"
    Invitations:
      $ref: "./components/schemas/invitation.yaml#/Invitations"
    Invitee:
      $ref: "./components/schemas/workspace.yaml#/Invitee"
    Invitees:
      $ref: "./components/schemas/workspace.yaml#/Invitees"
    MembershipPeriod:
      $ref: "./components/schemas/membership.yaml#/MembershipPeriod"
    Me:
      $ref: "./components/schemas/me.yaml#/Me"
    ReceivedInvitation:
      $ref: "./components/schemas/me.yaml#/ReceivedInvitation"
  requestBodies:
    AuthByOtpPost:
      $ref: "./components/requestBodies/auth.yaml#/AuthByOtpPost"
    AuthVerifyPost:
      $ref: "./components/requestBodies/auth.yaml#/AuthVerifyPost"
    CreateWorkspace:
      $ref: "./components/requestBodies/workspace.yaml#/CreateWorkspace"
    UpdateMeProfile:
      $ref: "./components/requestBodies/me.yaml#/UpdateMeProfile"
    UpdateMeProfilePhoto:
      $ref: "./components/requestBodies/me.yaml#/UpdateMeProfilePhoto"
    InvitationProcessEmail:
      $ref: "./components/requestBodies/auth.yaml#/InvitationProcessEmail"
    InvitationProcessOAuth:
      $ref: "./components/requestBodies/auth.yaml#/InvitationProcessOAuth"
    InvitationsBulk:
      $ref: "./components/requestBodies/member.yaml#/InvitationsBulk"
    UpdateMeMemberProfile:
      $ref: "./components/requestBodies/me.yaml#/UpdateMeMemberProfile"
    UpdateMemberRole:
      $ref: "./components/requestBodies/member.yaml#/UpdateMemberRole"
    UpdateWorkspace:
      $ref: "./components/requestBodies/workspace.yaml#/UpdateWorkspace"
  responses:
    GeneralError:
      $ref: "./components/responses/error.yaml#/components/responses/GeneralError"
    BadRequestError:
      $ref: "./components/responses/error.yaml#/components/responses/BadRequestError"
    ForbiddenError:
      $ref: "./components/responses/error.yaml#/components/responses/ForbiddenError"
    NotFoundError:
      $ref: "./components/responses/error.yaml#/components/responses/NotFoundError"
    UnauthorizedError:
      $ref: "./components/responses/error.yaml#/components/responses/UnauthorizedError"
    ConflictError:
      $ref: "./components/responses/error.yaml#/components/responses/ConflictError"
    GoneError:
      $ref: "./components/responses/error.yaml#/components/responses/GoneError"
    TooManyRequestsError:
      $ref: "./components/responses/error.yaml#/components/responses/TooManyRequestsError"
    InternalServerError:
      $ref: "./components/responses/error.yaml#/components/responses/InternalServerError"
    GetInvitationByTokenResponse:
      $ref: "./components/responses/auth.yaml#/GetInvitationByTokenResponse"
    InvitationsBulkResponse:
      $ref: "./components/responses/member.yaml#/InvitationsBulkResponse"
    RevokeInvitationResponse:
      $ref: "./components/responses/member.yaml#/RevokeInvitationResponse"
    ResendInvitationResponse:
      $ref: "./components/responses/member.yaml#/ResendInvitationResponse"
    WorkspacesResponse:
      $ref: "./components/responses/workspace.yaml#/WorkspacesResponse"
    InvitationsResponse:
      $ref: "./components/responses/member.yaml#/InvitationsResponse"
    MembersResponse:
      $ref: "./components/responses/member.yaml#/MembersResponse"
    MeResponse:
      $ref: "./components/responses/me.yaml#/MeResponse"
    UpdateProfileResponse:
      $ref: "./components/responses/me.yaml#/UpdateProfileResponse"
    UpdateProfilePhotoResponse:
      $ref: "./components/responses/me.yaml#/UpdateProfilePhotoResponse"
    RemoveProfilePhotoResponse:
      $ref: "./components/responses/me.yaml#/RemoveProfilePhotoResponse"
    UpdateMeMemberProfileResponse:
      $ref: "./components/responses/me.yaml#/UpdateMeMemberProfileResponse"
    InvitationsAcceptResponse:
      $ref: "./components/responses/me.yaml#/InvitationsAcceptResponse"
    CreateWorkspaceResponse:
      $ref: "./components/responses/workspace.yaml#/CreateWorkspaceResponse"
    LoginResponse:
      $ref: "./components/responses/auth.yaml#/LoginResponse"
    AuthVerifyOTPResponse:
      $ref: "./components/responses/auth.yaml#/AuthVerifyOTPResponse"
    AuthByOAuthResponse:
      $ref: "./components/responses/auth.yaml#/AuthByOAuthResponse"
    InvitationProcessOAuthResponse:
      $ref: "./components/responses/auth.yaml#/InvitationProcessOAuthResponse"
    UpdateMemberRoleResponse:
      $ref: "./components/responses/member.yaml#/UpdateMemberRoleResponse"
    UpdateWorkspaceResponse:
      $ref: "./components/responses/workspace.yaml#/UpdateWorkspaceResponse"
