openapi: 3.0.2
info:
  title: System API
  description: System API
  version: 1.0.0
tags:
  - name: Health
    description: Health Check
paths:
  /ping:
    $ref: "./paths/ping.yaml#/ping"
  /me:
    $ref: "./paths/me.yaml#/me"
  /sign_up:
    $ref: "./paths/sign_up.yaml#/sign_up"
  /login:
    $ref: "./paths/login.yaml#/login"

components:
  securitySchemes:
    $ref: "./components/securitySchemes/index.yaml#/securitySchemes"
