openapi: 3.0.2
info:
  title: System API
  description: System API
  version: 1.0.0
tags:
  - name: Health
    description: Health Check
paths:
  /ping:
    get:
      summary: Checks if the server is running
      responses:
        '200':
          description: Ping response
        '500':
          $ref: '#/components/responses/InternalServerError'
    post:
      summary: Checks if the server is running
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - name
              properties:
                name:
                  type: string
                  description: Name
                  example: John Doe
      responses:
        '200':
          description: Ping response
        '500':
          $ref: '#/components/responses/InternalServerError'
  /me:
    get:
      summary: Get Admin User
      description: Returns the admin user
      security:
        - bearer: []
      responses:
        '200':
          description: Admin User
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Me'
        '500':
          $ref: '#/components/responses/InternalServerError'
  /sign_up:
    post:
      summary: Sign Up
      description: Sign Up
      operationId: sign_up
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
              properties:
                name:
                  type: string
                  description: Name
                  example: John Doe
      responses:
        '200':
          description: Sign Up
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Me'
        '400':
          $ref: '#/components/responses/BadRequestError'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '500':
          $ref: '#/components/responses/InternalServerError'
  /login:
    post:
      summary: Login
      description: Login
      operationId: login
      responses:
        '200':
          description: Login response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Me'
        '500':
          $ref: '#/components/responses/InternalServerError'
components:
  securitySchemes:
    bearer:
      type: http
      description: JWT Token Authentication
      scheme: bearer
      bearerFormat: JWT
  schemas:
    User:
      type: object
      required:
        - userId
        - email
        - name
      properties:
        userId:
          type: string
          format: uuid
        email:
          type: string
          format: email
        name:
          type: string
        phoneNumber:
          type: string
    MultiFactor:
      type: object
      required:
        - factorId
        - phoneNumber
      properties:
        factorId:
          type: string
        phoneNumber:
          type: string
    Workspace:
      type: object
      required:
        - workspaceId
        - name
      properties:
        workspaceId:
          type: string
          format: uuid
        name:
          type: string
    Member:
      type: object
      required:
        - user
      properties:
        idNumber:
          type: string
        user:
          $ref: '#/components/schemas/User'
    Me:
      type: object
      required:
        - emailVerified
        - member
      properties:
        emailVerified:
          type: boolean
          default: false
        multiFactor:
          $ref: '#/components/schemas/MultiFactor'
        member:
          $ref: '#/components/schemas/Member'
  responses:
    GeneralError:
      description: General Error
      content:
        application/json:
          schema:
            type: object
            description: RFC7807 - https://datatracker.ietf.org/doc/html/rfc7807
            properties:
              status:
                type: integer
                example: 400
                description: >-
                  The HTTP status code generated for this occurrence of the
                  problem.
              type:
                type: string
                example: invalid_item_id
                description: error type
              title:
                type: string
                description: A short, human-readable summary of the problem type
              detail:
                type: string
                description: >-
                  A human-readable explanation specific to this occurrence of
                  the problem.
              code:
                type: string
                example: invalid_item_id
                description: error code
    UnauthorizedError:
      description: Unauthorized
      content:
        application/json:
          schema:
            type: object
            description: RFC7807 - https://datatracker.ietf.org/doc/html/rfc7807
            properties:
              status:
                type: integer
                example: 400
                description: >-
                  The HTTP status code generated for this occurrence of the
                  problem.
              type:
                type: string
                example: invalid_item_id
                description: error type
              title:
                type: string
                description: A short, human-readable summary of the problem type
              detail:
                type: string
                description: >-
                  A human-readable explanation specific to this occurrence of
                  the problem.
              code:
                type: string
                example: invalid_item_id
                description: error code
    NotFoundError:
      description: Entity not found.
      content:
        application/json:
          schema:
            type: object
            description: RFC7807 - https://datatracker.ietf.org/doc/html/rfc7807
            properties:
              status:
                type: integer
                example: 400
                description: >-
                  The HTTP status code generated for this occurrence of the
                  problem.
              type:
                type: string
                example: invalid_item_id
                description: error type
              title:
                type: string
                description: A short, human-readable summary of the problem type
              detail:
                type: string
                description: >-
                  A human-readable explanation specific to this occurrence of
                  the problem.
              code:
                type: string
                example: invalid_item_id
                description: error code
    BadRequestError:
      description: Bad request
      content:
        application/json:
          schema:
            type: object
            description: RFC7807 - https://datatracker.ietf.org/doc/html/rfc7807
            properties:
              status:
                type: integer
                example: 400
                description: >-
                  The HTTP status code generated for this occurrence of the
                  problem.
              type:
                type: string
                example: invalid_item_id
                description: error type
              title:
                type: string
                description: A short, human-readable summary of the problem type
              detail:
                type: string
                description: >-
                  A human-readable explanation specific to this occurrence of
                  the problem.
              code:
                type: string
                example: invalid_item_id
                description: error code
    InternalServerError:
      description: Internal server error
      content:
        application/json:
          schema:
            type: object
            description: RFC7807 - https://datatracker.ietf.org/doc/html/rfc7807
            properties:
              status:
                type: integer
                example: 400
                description: >-
                  The HTTP status code generated for this occurrence of the
                  problem.
              type:
                type: string
                example: invalid_item_id
                description: error type
              title:
                type: string
                description: A short, human-readable summary of the problem type
              detail:
                type: string
                description: >-
                  A human-readable explanation specific to this occurrence of
                  the problem.
              code:
                type: string
                example: invalid_item_id
                description: error code
