name: __ Go CI

on:
  workflow_call:
    inputs:
      directory:
        description: 'Target directory'
        required: true
        type: string

permissions:
  contents: read

jobs:
  go-versions:
    uses: ./.github/workflows/__go-latest-versions.yml

  ci:
    needs: [ go-versions ]
    name: "Run CI"
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        go-version: ${{fromJson(needs.go-versions.outputs.versions)}}
    runs-on: ${{ matrix.os }}
    working-directory: ${{ inputs.directory }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - uses: WillAbides/setup-go-faster@v1.7.0
        with:
          go-version: ${{ matrix.go }}

      - run: "go vet ./..."

      - uses: dominikh/staticcheck-action@v1.2.0
        with:
          version: "2022.1.1"
          install-go: false
          cache-key: ${{ matrix.go }}

      - name: Install tparse
        run: go install github.com/mfridman/tparse@latest

      - name: Test
        shell: bash
        run: |
          set -o pipefail
          go test ./... -json | tee ./go-test.out | tparse -all

      - name: Add job summary
        shell: bash
        if: always()
        run: |
          tparse -file ./go-test.out -format markdown >> $GITHUB_STEP_SUMMARY
