name: __ Go CI

on:
  workflow_call:
    inputs:
      directory:
        description: 'Target directory'
        required: true
        type: string

permissions:
  contents: read

jobs:
  go-version:
    uses: ./.github/workflows/__go-version-from-mod.yml
    with:
      directory: ${{ inputs.directory }}

  ci:
    needs: [go-version]
    defaults:
      run:
        working-directory: ${{ inputs.directory }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v4
        with:
          go-version: '${{ needs.go-version.outputs.go-version }}'
          cache: true

      - name: Get dependencies
        run: go mod download

      - name: go vet
        run: go vet ./...

      - name: Install Staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Run Staticcheck
        run: staticcheck ./...

      - name: Install tparse
        run: go install github.com/mfridman/tparse@latest

      - name: Test
        run: |
          set -o pipefail
          go test ./... -json | tee ./go-test.out | tparse -all

      - name: Add job summary
        shell: bash
        run: |
          tparse -file ./go-test.out -format markdown >> $GITHUB_STEP_SUMMARY
