name: __ Javascript CI

on:
  workflow_call:
    inputs:
      directory:
        description: 'Target directory'
        required: true
        type: string

permissions:
  contents: read

jobs:
  node-version:
    uses: ./.github/workflows/__node-version.yml

  pnpm-version:
    uses: ./.github/workflows/__pnpm-version.yml

  ci:
    needs: [ node-version, pnpm-version ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: ${{ inputs.pnpm-version }}

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: lint on CI
        run: pnpm ci --filter ${{ inputs.directory }}

      - name: test on CI
        run: pnpm test --filter ${{ inputs.directory }}
