name: __ Go CI With Container

on:
  workflow_call:
    inputs:
      directory:
        description: 'Target directory'
        required: true
        type: string

permissions:
  contents: read

jobs:
  go-version:
    uses: ./.github/workflows/__go-version-from-mod.yml
    with:
      directory: ${{ inputs.directory }}

  ci-with-container:
    needs: [go-version]
    defaults:
      run:
        working-directory: ${{ inputs.directory }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-go@v5
        with:
          go-version: '${{ needs.go-version.outputs.go-version }}'
          cache: true

      - name: Get dependencies
        run: go mod download

      - name: Install tparse
        run: go install github.com/mfridman/tparse@latest

      - name: Test
        run: |
          set -o pipefail
          go test -v -count=1 -race -shuffle=on ./... -tags='testcontainers' -json | tee ./go-test.out | tparse -all

      - name: Add job summary
        shell: bash
        run: |
          tparse -file ./go-test.out -format markdown >> $GITHUB_STEP_SUMMARY
