name: __ Go CI

on:
  workflow_call:
    inputs:
      directory:
        description: 'Target directory'
        required: true
        type: string

permissions:
  contents: read

jobs:
  go-version:
    uses: ./.github/workflows/__go-version-from-mod.yml
    with:
      directory: ${{ inputs.directory }}

  ci:
    needs: [go-version]
    defaults:
      run:
        working-directory: ${{ inputs.directory }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '${{ needs.go-version.outputs.go-version }}'
          cache: true

      - name: Go Tidy
        run: go mod tidy && git diff --exit-code

      - name: Get dependencies
        run: go mod download

      - name: Install Staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Run Staticcheck
        run: staticcheck ./...

      - name: go vet
        run: go vet ./...

      - name: Run Gosec Security Scanner
        uses: securego/gosec@master
        with:
          args: '-no-fail -fmt html -out results.html ./...'

      - name: Upload Gosec results
        uses: actions/upload-artifact@v5
        with:
          name: gosec-results
          path: results.html

      - name: Install gomockhandler
        run: |
          go install go.uber.org/mock/mockgen@latest
          go install github.com/sanposhiho/gomockhandler@latest

      - name: Go Generate
        run: go generate ./... && git diff --exit-code

      - name: Install tparse
        run: go install github.com/mfridman/tparse@latest

      - name: Test
        run: |
          set -o pipefail
          go test -v -count=1 -race -shuffle=on ./... -tags='!testcontainers' -json | tee ./go-test.out | tparse -all

      - name: Add job summary
        shell: bash
        run: |
          tparse -file ./go-test.out -format markdown >> $GITHUB_STEP_SUMMARY
