name: __ Javascript CI

on:
  workflow_call:
    inputs:
      directory:
        description: 'Target directory'
        required: true
        type: string

permissions:
  contents: read

jobs:
  node-version:
    uses: ./.github/workflows/__node-version.yml
    with:
      directory: ${{ inputs.directory }}

  pnpm-version:
    uses: ./.github/workflows/__pnpm-version.yml
    with:
      directory: ${{ inputs.directory }}

  ci:
    needs: [node-version, pnpm-version]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ needs.node-version.outputs.node-version }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{ needs.pnpm-version.outputs.pnpm-version }}

      - name: Get pnpm store directory
        id: pnpm-store
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-store.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: lint on CI
        run: pnpm run ci --filter ${{ inputs.directory }}

      - name: Build packages
        run: pnpm run package:build

      - name: test on CI
        run: pnpm run test --filter ${{ inputs.directory }}
