name: __ get latest go versions

on:
  workflow_call:
    outputs:
      go-versions:
        description: 'Go versions'
        value: ${{ github.event.inputs.go-versions }}

jobs:
  get-go-versions:
    runs-on: ubuntu-latest
    outputs:
      go-versions: ${{ steps.go-versions.outputs.versions }}
    steps:
      - uses: actions/checkout@v5

      - name: Read Go versions
        id: go-versions
        run: |
          versions=$(curl -s 'https://go.dev/dl/?mode=json' | jq -c 'map(.version[2:])')
          echo "versions=$versions" >> "$GITHUB_OUTPUT"

      - name: Echo Go version
        run: echo "Go version is ${{ steps.go-versions.outputs.versions }}"
