name: __ unit test go

on:
  workflow_call:
    inputs:
      go-version:
        description: 'Go version'
        required: true
        type: string
      directory:
        description: 'Target directory'
        required: true
        type: string

jobs:
  go-unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ inputs.go-version }}
          cache: true
          cache-dependency-path: go.sum

      - name: Get dependencies
        shell: bash
        run: go get -v -t -d ./...

      - name: Go Build
        shell: bash
        run: |
          go build -v ./...

      - name: Go Test
        shell: bash
        run: |
          go test -short -bench . -benchmem ./...
