name: __ get Go version from go.mod

on:
  workflow_call:
    inputs:
      directory:
        required: false
        type: string
        default: '.'

jobs:
  get-go-version:
    runs-on: ubuntu-latest
    outputs:
      go-version: ${{ steps.go-version.outputs.version }}
    steps:
      - uses: actions/checkout@v4

      - name: Read go version from go.mod
        id: go-version
        run: |
          go_version=$(cat ${{ inputs.directory }}/go.mod | grep -Eo 'go [0-9]+\.[0-9]+' | awk '{print $2}')
          echo "version=$go_version" >> "$GITHUB_OUTPUT"

      - name: Echo Go version
        run: echo "Go version is ${{ steps.go-version.outputs.version }}"
