name: __ Lint Dockerfile

on:
  workflow_call:
    inputs:
      directory:
        description: 'Target directory'
        required: true
        type: string

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: ${{ inputs.directory }}/Dockerfile
