name: __ Lint Go

on:
  workflow_call:
    inputs:
      directory:
        description: 'Target directory'
        required: true
        type: string
      go-version:
        description: 'go version'
        required: true
        type: string

permissions:
  contents: read

jobs:
  golangci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v4
        with:
          go-version: ${{ needs.go-version.outputs.go-version }}
          cache: false

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          working-directory: ${{ inputs.directory }}
          version: v${{ inputs.go-version }}
