name: __ get node version from target directory

on:
  workflow_call:
    inputs:
      directory:
        required: false
        type: string
        default: '.'

jobs:
  get-node-version:
    runs-on: ubuntu-latest
    outputs:
      node-version: ${{ steps.node-version.outputs.version }}
    steps:
      - uses: actions/checkout@v4

      - name: Read Node.js version from .tool-versions
        id: node-version
        run: |
          node_version=$(grep nodejs ${{ inputs.directory }}/.tool-versions | cut -d ' ' -f2)
          echo "version=$node_version" >> "$GITHUB_OUTPUT"
