name: __ get node version from target directory

on:
  workflow_call:
    inputs:
      directory:
        required: false
        type: string
        default: '.'
    outputs:
      node-version:
        description: "node version"
        value: ${{ jobs.get-node-version.outputs.node-version }}
      major-version:
        description: "node major version"
        value: ${{ jobs.get-node-version.outputs.major-version }}

jobs:
  get-node-version:
    runs-on: ubuntu-latest
    outputs:
      node-version: ${{ steps.node-version.outputs.version }}
      major-version: ${{ steps.node-major-version.outputs.major-version }}
    steps:
      - uses: actions/checkout@v4

      - name: Read Node.js version from .tool-versions
        id: node-version
        run: |
          node_version=$(grep nodejs ${{ inputs.directory }}/.tool-versions | cut -d ' ' -f2)
          echo "version=$node_version" >> "$GITHUB_OUTPUT"

      - name: Get Node.js major version
        id: node-major-version
        run: |
          node_major_version=$(echo ${{ steps.node-version.outputs.version }} | cut -d '.' -f1)
          echo "major-version=$node_major_version" >> "$GITHUB_OUTPUT"

      - name: Echo Node.js version
        run: echo "Node.js version is ${{ steps.node-version.outputs.version }}"
