name: __ get pnpm version from target directory

on:
  workflow_call:
    inputs:
      directory:
        required: false
        type: string
        default: '.'

jobs:
  get-pnpm-version:
    runs-on: ubuntu-latest
    outputs:
      pnpm-version: ${{ steps.pnpm-version.outputs.version }}
    steps:
      - uses: actions/checkout@v4

      - name: Read pnpm version from package.json
        id: pnpm-version
        run: |
          pnpm_version=$(cat ${{ inputs.directory }}/package.json | jq -r .engines.pnpm)
          echo "version=$pnpm_version" >> "$GITHUB_OUTPUT"

      - name: Echo pnpm version
        run: echo "pnpm version is ${{ steps.pnpm-version.outputs.version }}"