name: Format proto

on:
  push:
    branches: [ main ]
    paths:
      - '**/*.proto'
      - .github/workflows/formatter-proto.yml
      - '!**/generated/**'

permissions:
  id-token: write
  contents: write

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: bufbuild/buf-setup-action@v1.28.1

      - name: Proto format
        run: buf format -w --diff

      - name: Check diff
        id: diff
        shell: bash
        continue-on-error: true
        run: |
          git add -N .
          git diff --name-only --exit-code

      - name: Commit changes
        if: steps.diff.outcome == 'failure'
        shell: bash
        run: |
          set -x
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add .
          git commit -m "🚗 format proto file by github-actions"

      - name: Push changes
        if: steps.diff.outcome == 'failure'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.head_ref }}
