name: System main pipeline

on:
  push:
    branches: [ main ]
    paths:
      - apps/system/**
      - .github/workflows/system-main-pipeline.yml
      - .github/workflows/__ci-js.yml
      - .github/workflows/__ci-go.yml
      - .github/workflows/__lint-docker.yml

jobs:
  lint-api-dockerfile:
    uses: ./.github/workflows/__lint-docker.yml
    strategy:
      matrix:
        dockerfile:
          - './apps/system/api'
    with:
      directory: ${{ matrix.dockerfile }}

  ci-go:
    uses: ./.github/workflows/__ci-go.yml
    with:
      directory: ./apps/system/api

  ci-js:
    uses: ./.github/workflows/__ci-js.yml
    with:
      directory: ./apps/system/client
