name: System main pipeline

run-name: System main pipeline - ${{ github.sha }}

on:
  push:
    branches: [main]
    paths:
      - apps/system/**
      - .github/workflows/system-main-pipeline.yml
      - .github/workflows/__ci-js.yml
      - .github/workflows/__ci-go.yml
      - .github/workflows/__lint-docker.yml

jobs:
  ci-docker:
    uses: ./.github/workflows/__lint-docker.yml
    with:
      directory: './apps/system/api'

  ci-go:
    uses: ./.github/workflows/__ci-go.yml
    with:
      directory: './apps/system/api'

  ci-js:
    uses: ./.github/workflows/__ci-js.yml
    with:
      directory: './apps/system/client'

  # Execute before deploy
  # ci-go-with-container:
  #   uses: ./.github/workflows/__ci-go-with-container.yml
  #   with:
  #     directory: './apps/system/api'
